version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: fallstudie-db
    environment:
      MYSQL_DATABASE: fallstudie
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./fallstudie-db.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
